# Generated by Django 5.0.3 on 2024-03-24 18:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieRecommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereviewmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moviereviewmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
