# Generated by Django 5.0.3 on 2024-03-24 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieRecommender', '0002_moviereviewmodel_date_alter_moviereviewmodel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviereviewmodel',
            old_name='id',
            new_name='Reviewid',
        ),
    ]
