# Generated by Django 5.0.3 on 2024-03-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieRecommender', '0003_rename_id_moviereviewmodel_reviewid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereviewmodel',
            name='Review',
            field=models.IntegerField(max_length=3),
        ),
    ]
