# Generated by Django 5.0.3 on 2024-03-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieRecommender', '0004_alter_moviereviewmodel_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviereviewmodel',
            old_name='Review',
            new_name='Rating',
        ),
    ]
